export { AddIcon } from "./AddIcon";
export { default as SearchIcon } from "./SearchIcon";
export { default as GradientGraduateIcon } from "./GradientGraduateIcon";
export { default as LinkedlnIcon } from "./LinkedlnIcon";
export { default as AnalystIcon } from "./AnalystIcon";
export { default as DropdownArrowIcon } from "./DropdownArrowIcon";
export { default as UserIcon } from "./UserIcon";
export { default as GradientEditIcon } from "./GradientEditIcon";
export { default as GradientSettingIcon } from "./GradientSettingIcon";
export { default as GradientLogoutIcon } from "./GradientLogoutIcon";
export { default as DeleteIcon } from "./DeleteIcon";
export { default as GoogleIcon } from "./GoogleIcon";
export { default as PasswordEyeIcon } from "./PasswordEyeIcon";
export { CandidateProfilePlaceholder } from "./CandidateProfilePlaceholder";
export { TickIconDesktop, TickIconMobile, TickIconSubmit } from "./TickIcons";
export { ShowPasswordIcon } from "./ShowPasswordIcon";
export { HidePasswordIcon } from "./HidePasswordIcon";
export { DownloadIcon } from "./DownloadIcon";
export { default as ExternalLinkIcon } from "./ExternalLinkIcon";
export { SeniorityIcon } from "./Seniority";
export { default as UserBlueIcon } from "./UserBlueIcon";

export { BuildingIcon } from "./Unicons";
export { UpArrowIcon } from "./Unicons";
export { RightArrowIcon } from "./Unicons";
export { LeftArrowIcon } from "./Unicons";
export { LocationIcon } from "./Unicons";
export { TwitterIcon } from "./Unicons";
export { FacebookIcon } from "./Unicons";
export { LocationPinIcon } from "./Unicons";
export { ClockIcon } from "./Unicons";
export { BriefcaseIcon } from "./Unicons";
export { NewspaperIcon } from "./Unicons";
export { CoinsIcon } from "./Unicons";
export { GraduateIcon } from "./Unicons";
export { EyeIcon } from "./Unicons";
export { AppleIcon } from "./Unicons";
export { UilFile } from "./Unicons";
export { UilFileDownload } from "./Unicons";

export * as UniconsLibraryIcons from "./Unicons";
export * as DJobsGradientIcons from "./GradientIcons";
export * as SocialMediaIcons from "./SocialMediaIcons";