import { CommonCandidateDetails } from "../Candidate";

const candidate: CommonCandidateDetails.Candidate = {
  candidateId: 1,
  name: "Jane Doe Smith",
  firstName: "Jane Doe",
  lastName: "Smith",
  country: "ZA",
  city: "Cape town",
  profilePicture: `/static/images/company-profile-image.jpg`,
  rating: "Good fit",
  telephone: 5555555555,
  email: "email@domain.com",
  status: "onboarding",
  dateApplied: "10/05/2022",
  role: "React developer",
  about:
    "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
  skills: "REACT",
  languages: [{ language: "English", proficiency: "Full" }],
};

const candidateList: CommonCandidateDetails.CandidateList = [
  {
    candidateId: 1,
    name: "Jane Doe-Smith",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Good fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "onboarding",
    dateApplied: "10/05/2022",
    role: "React developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 2,
    name: "Becky Jane",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Maybe",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "interview",
    dateApplied: "28/04/2022",
    role: "Backend developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 3,
    name: "Joe Smith",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Good fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "offer made",
    dateApplied: "31/03/2022",
    role: "Backend developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 4,
    name: "Martin Bale",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Good fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "offer made",
    dateApplied: "07/05/2022",
    role: "React developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 5,
    name: "Michael Jackson",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Bad fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "screening",
    dateApplied: "30/04/2022",
    role: "Senior architect",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 6,
    name: "Jenny Darling",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Maybe",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "screening",
    dateApplied: "26/04/2022",
    role: "React developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 7,
    name: "Bobby Slater",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Bad fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "screening",
    dateApplied: "27/04/2022",
    role: "React developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 8,
    name: "Bobby Slater",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Bad fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "interview",
    dateApplied: "30/04/2022",
    role: "Senior architect",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
  {
    candidateId: 9,
    name: "Bobby Slater",
    country: "ZA",
    city: "Cape town",
    profilePicture: `/static/images/company-profile-image.jpg`,
    rating: "Bad fit",
    telephone: 5555555555,
    email: "email@domain.com",
    status: "shortlist",
    dateApplied: "15/05/2022",
    role: "React developer",
    about:
      "I am currently looking for a Digital Design Intern with wililing to join any awesome team in Cape Town. I am a effective designer actively involving in campaigns and managing a number of projects within tight deadlines. ",
    skills: "REACT",
    languages: [{ language: "English", proficiency: "Full" }],
  },
];

export const sampleCandidateDataInCommon = {
  candidateList,
  candidate,
};
