const deadline = "2022/06/30";
export const jobsTableData = [
  {
    datePosted: "2022/01/01",
    status: "Active",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Draft",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Draft",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Expired",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Expired",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Active",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Expired",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Active",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Draft",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Expired",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Draft",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Expired",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Active",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Expired",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Draft",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Active",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Expired",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Draft",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Expired",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Expired",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Expired",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Active",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Active",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Draft",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Expired",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Draft",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Draft",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/03/22",
    status: "Active",
    jobTitle: "Next.JS",
    location: "Canada",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Expired",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
  {
    datePosted: "2022/01/01",
    status: "Expired",
    jobTitle: "React.JS",
    location: "Cape Town",
    unread: Math.floor(Math.random() * 10) || 8,
    applied: Math.floor(Math.random() * 10) || 8,
    endDate: deadline,
  },
  {
    datePosted: "2022/02/14",
    status: "Active",
    jobTitle: "Node.JS",
    location: "USA",
    unread: 2,
    applied: 2,
    endDate: deadline,
  },
];

export const menuItemsData = [
  {
    value: "ALL",
    label: "ALL",
  },
  {
    value: "ACTIVE",
    label: "ACTIVE",
  },
  { value: "DRAFT", label: "DRAFT" },
  { value: "EXPIRED", label: "EXPIRED" },
];

export const jobsTableColumnsData = [
  {
    Header: "Date Posted",
    accessor: "datePosted",
  },
  {
    Header: "Status",
    accessor: "status",
  },
  {
    Header: "Job Title",
    accessor: "jobTitle",
  },
  {
    Header: "Location",
    accessor: "location",
  },
  {
    Header: "Unread",
    accessor: "unread",
  },
  {
    Header: "Applied",
    accessor: "applied",
  },
  {
    Header: "End Date",
    accessor: "endDate",
  },
  {
    Header: "Actions",
    accessor: "actions",
    disableSortBy: true,
  },
];
