import { GlobalTheme } from "@Global/Theme/styled";
declare module DjobsTheme {
  type DJStyleObject = {
    sm: GlobalTheme.StyleObject;
    md?: GlobalTheme.StyleObject;
    lg?: GlobalTheme.StyleObject;
    xl?: GlobalTheme.StyleObject;
  };

  export type DjobsColors = {
    dittoBlue: string;
    textDefault: string;
    textDarker: string;
    grey10: string;
    black110: string;
    black30: string;
    black40: string;
    black95: string;

    blue20: string;
    blue30: string;
    blue40: string;
    blue70: string;
    blue80: string;
    blue90: string;
    blue100: string;
    blue200: string;

    purple50: string;

    blueGrey90: string;

    grey20: string;
    darkBlueGrey: string;
    inputBg: string;
    black05: string;
    white90: string;
    specialGreen: string;
    countryHoverBackground: string;
    InputFilledBorder: string;
    horizontalLineColor: string;
  };
  export type DjobsGradients = {
    purple20: string;
    jobInsideAccent: string;
    red100: string;
    jobViewAccent: string;
    aditionalAccent: string;
    dragAndDropHover: string;
    homeMobileGradient: string;
    countrySelectorPopup: string;
    searchPopupcontainer: string;
    djsearchPopupcontainer: string;
    blue80: string;
    disabledBg: string;
  };
  export type DjobsText = {
    accordianSubTitle: DJStyleObject;
    djErrorPageTitle: DJStyleObject;
    djErrorPageRegular: DJStyleObject;
    djCardsCompanyAlt: DJStyleObject;
    djInputRegular: DJStyleObject;
    djCareerNotFoundMsg: DJStyleObject;
    djHeaderInputInitial: DJStyleObject;
    djTitleCase: DJStyleObject;
    djTextRegular: DJStyleObject;

    djTextMedium: DJStyleObject;
    djAlertDescription: DJStyleObject;
    djPillTitle: DJStyleObject;
    djPillRegular: DJStyleObject;
    djPillLabel: DJStyleObject;
    djPillBold: DJStyleObject;
    djPlaceholder: DJStyleObject;
    djTitleOne: DJStyleObject;
    djTitleTwo: DJStyleObject;
    djSubTitleOne: DJStyleObject;
    djSubTitleTwo: DJStyleObject;
    djSubTitleThree: DJStyleObject;
    djSubTitleFour: DJStyleObject;
    djSubTitleSix: DJStyleObject;
    djBodySmall: DJStyleObject;
    djBody: DJStyleObject;
    djBodyRegular: DJStyleObject;
    djIconPrefixRegular: DJStyleObject;
    djTagsRegular: DJStyleObject;
    djHeadingOne: DJStyleObject;
    djHeadingTwo: DJStyleObject;
    djHeadingThree: DJStyleObject;
    djHeadingFour: DJStyleObject;
    djForms: DJStyleObject;
    djSubHeadingTwo: DJStyleObject;
    djCapsRegular: DJStyleObject;
    djCapsSmall: DJStyleObject;
    djSignButtonText: DJStyleObject;
    djBold: DJStyleObject;
    djStamp: DJStyleObject;
    djCardStamp: DJStyleObject;
    djLinkSmall: DJStyleObject;
    djLinkRegular: DJStyleObject;
    djLinkBold: DJStyleObject;
    djHeadMenu: DJStyleObject;
    djApplyButton: DJStyleObject;
    djIconText: DJStyleObject;
    djButtonIcon: DJStyleObject;
    djTextBold: DJStyleObject;
    djTextExtraSmallRegular: DJStyleObject;
    djCardsTitle: DJStyleObject;
    djCardsCompany: DJStyleObject;
    djIconsText: DJStyleObject;
    djIcons: DJStyleObject;
    djIconRegular: DJStyleObject;
    djSmall: DJStyleObject;
    djSmallText: DJStyleObject;
    djLexendRegularCaps: DJStyleObject;
    djLexendBoldCaps: DJStyleObject;
    djHeadingOne: DJStyleObject;
    djHeaderTwo: DJStyleObject;
    djLocation: DJStyleObject;
    djRegular: DJStyleObject;
    djTabDefault: DJStyleObject;
    djActiveTabDefault: DJStyleObject;
    djCardsTitle: DJStyleObject;
    djCardsCompany: DJStyleObject;
    djUploadDocText: DJStyleObject;
    djTitleThree: DJStyleObject;
    djBackButtonText: DJStyleObject;
    djSubHeadingThree: DJStyleObject;
    djFileTitle: DJStyleObject;
    djFileSize: DJStyleObject;
    djHeadingSix: DJStyleObject;
    djCloseAccountText: DJStyleObject;
    djCountText: DJStyleObject;
    djButtonNext: DJStyleObject;

    djFormsRegular: DJStyleObject;
    djInputLabel: DJStyleObject;
    djInputPlaceholder: DJStyleObject;
    djInputError: DJStyleObject;
    djInputRequiredLabel: DJStyleObject;
    djInputValue: DJStyleObject;
    djSelectFieldOption: DJStyleObject;
    djReviewSubtitle: DJStyleObject;
    djSuccessHeading: DJStyleObject;
    djSuccessSubHeading: DJStyleObject;
    candidateSettingHeadingOne: DJStyleObject;
    djLinkRegular: DJStyleObject;
    djForgotLinkRegular: DJStyleObject;
    djCloseLinkAllCaps: DJStyleObject;
    djAdInputData: DJStyleObject;
    djAdInputLabel: DJStyleObject;
    djTabNavActive: DJStyleObject;
    djTabNavDefault: DJStyleObject;
    djAdInputLabel: DJStyleObject;
    djAdInputData: DJStyleObject;
    djAdSubTitleThree: DJStyleObject;
    djUploadFileTextGif: DJStyleObject;
    djUploadFileText: DJStyleObject;
    djUploadFileSizeText: DJStyleObject;
    djFooter: DJStyleObject;
    djFooterSubLink: DJStyleObject;
    djFooterMainLInk: DJStyleObject;
    djFooterText: DJStyleObject;
    djcountryList: DJStyleObject;
    djCookiesHeading: DJStyleObject;
    djLegalHeading: DJStyleObject;
    djLegalSubHeading: DJStyleObject;
    djLegalTabNavDefault: DJStyleObject;
    djLegalTabNavActive: DJStyleObject;
    djModal: DJStyleObject;
    djButtonText: DJStyleObject;
    djCardsTitle: DJStyleObject;
    djCapitalBold: DJStyleObject;

    djBTNSRegular: DJStyleObject;
    djBTNSSecondary: DJStyleObject;
    djBTNSTertitary: DJStyleObject;
    djJobviewDescription: DJStyleObject;
    djJobviewHeading: DJStyleObject;
    djJobDetailCard: DJStyleObject;
  };
  export type DjobsEffects = {
    jobTilesShadow: string;
    inputInnerShadow: string;
    cards: string;
    cardShadow: string;
    tagsShadow: string;
    activeBorder: string;
    questionairresBox: string;
    PlainButton: string;
    plainHoverState: string;
    activeHoverState: string;
    signInButtonShadow: string;
    switchInputShadow: string;
    switchButtonShadow: string;
    defaultButtonShadow: string;
    secondaryButtonShadow: string;
    textShadow: string;
    mainButton: string;
    mainButtonHoverShadow: string;
    aditionalShadow: string;
    dragDropHoverShadow: string;
    jobCardShadow: string;
    greenShadow: string;
    popUpShadow: string;
    countryPopupShadow: string;
    dropShadow: string;
    modals: string;
    citydropdownItemShadow: string;
    countryHoverBackgroundShadow: string;
    errorOutline: string;
    socialAuthBtnShadow: string;

    inputShadow: string;
    buttonNormal: string;
    buttonHoverState: string;
    buttonClick: string;
    shadowsStandard: string;
    menusBtnHoverNoBevel: string;
    primaryDisabledBg: string;
    jobContainerShadow: string;
    buttons: string;
  };

  export type DjobsColorsWithGlobal = DjobsColors & GlobalTheme.Colors;
  export type DjobsGradientsWithGlobal = DjobsGradients & GlobalTheme.Gradients;
  export type DjobsTextWithGlobal = DjobsText & GlobalTheme.Text;
  export type DjobsEffectsWithGlobal = DjobsEffects & GlobalTheme.Effects;

  export interface DefaultTheme {
    colors: DjobsColorsWithGlobal;
    gradients: DjobsGradientsWithGlobal;
    text: DjobsTextWithGlobal;
    effects: DjobsEffectsWithGlobal;
  }
}

export { DjobsTheme };
