export const regionNames = {
  AO: "Angola",
  AU: "Australia",
  AT: "Austria",
  BE: "Belgium",
  CM: "Cameroon",
  CA: "Canada",
  CI: "Côte d’Ivoire",
  CZ: "Czech Republic",
  FR: "France",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  HU: "Hungary",
  IN: "India",
  IE: "Ireland",
  IT: "Italy",
  KE: "Kenya",
  LU: "Luxembourg",
  MZ: "Mozambique",
  NL: "Netherlands",
  NZ: "New Zealand",
  NG: "Nigeria",
  PT: "Portugal",
  RO: "Romania",
  SN: "Senegal",
  ZA: "South Africa",
  ES: "Spain",
  CH: "Switzerland",
  UG: "Uganda",
  GB: "United Kingdom",
  US: "United States",
  ZM: "Zambia",
};
