const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
const GOOGLE_PROJECT_ID = process.env.NEXT_PUBLIC_GOOGLE_PROJECT_ID;

const FACEBOOK_APP_ID = process.env.NEXT_PUBLIC_FACEBOOK_APP_ID;

const LINKEDIN_CLIENT_ID = process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID;

export const SOCIAL_AUTH_IDS = {
  GOOGLE_CLIENT_ID,
  GOOGLE_PROJECT_ID,
  FACEBOOK_APP_ID,
  LINKEDIN_CLIENT_ID,
};
